config/routes.rb
Rails.application.routes.draw do

  devise_for :podcasts

  resources :podcasts, only: [:index, :show] do
    resources :episodes
  end

  authenticated :podcast do
    root 'podcasts#dashboard', as: "authenticated_root"
  end

  root 'welcome#index'

  

end

app/models/episode.rb
class Episode < ActiveRecord::Base
  belongs_to :podcast

  has_attached_file :thumbnail, styles: { medium: "300x300#", thumb: "160x160#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :thumbnail, content_type: /\Aimage\/.*\Z/

  has_attached_file :mp3
  validates_attachment :mp3, content_type: { content_type: ["audio/mpeg", "audio/mp3"] }, file_name: { matches: [/mp3\Z/] }

end

app/models/podcast.rb
class Podcast < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :title, presence: true, length: {maximum: 100}
  validates :description, presence: true, length: {maximum: 700}
  validates :thumbnail, presence: true

  has_many :episodes

  has_attached_file :thumbnail, styles: { medium: "300x300#", thumb: "160x160#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :thumbnail, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :title, :thumbnail, :description)}
  	devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :current_password, :title, :description, :itunes, :stitcher, :podbay, :thumbnail)}
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
	before_action :authenticate_podcast!, except: [:show]
	before_filter :require_permission
	before_action :find_podcast
	before_action :find_episode, only: [:show, :edit, :update, :destroy]

	def new 
		@episode = @podcast.episodes.new
	end

	def create
		@episode = @podcast.episodes.new episode_params
		if @episode.save
			redirect_to podcast_episode_path(@podcast, @episode)
		else
			render 'new'
		end
	end

	def show
		@episodes = Episode.where(podcast_id: @podcast).order("created_at desc").reject { |e| e.id == @episode.id }
	end

	def edit
	end

	def update
		if @episode.update episode_params
			redirect_to podcast_episode_path(@podcast, @episode), notice: "Episode was successfully updated!"
		else
			render 'edit'
		end
	end

	def destroy
		@episode.destroy
		redirect_to root_path
	end

	private

		def episode_params
			params.require(:episode).permit(:title, :description, :thumbnail, :mp3)
		end

		def find_podcast
			@podcast = Podcast.find(params[:podcast_id])
		end

		def find_episode
			@episode = Episode.find(params[:id])
		end

		def require_permission
			@podcast = Podcast.find(params[:podcast_id])
			if current_podcast != @podcast
				redirect_to root_path, notice: "Sorry, you're not allowed to view that page."
			end
		end
end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
	before_action :find_podcast, only: [:show, :dashboard]
	before_action :find_episode, only: [:show, :dashboard]

	def index
		@podcasts = Podcast.all.order("created_at desc")
		@episodes = Episode.where(podcast_id: @podcast)
	end

	def show
	end

	def dashboard
	end

	private

		def find_episode
			@episodes = Episode.where(podcast_id: @podcast).order("created_at desc")
		end

		def find_podcast
			if params[:id].nil?
				@podcast = current_podcast
			else
				@podcast = Podcast.find(params[:id])
			end
		end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
		
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/views/episodes/_form.html.erb
<%= form_for ([@podcast, @episode]) do |f| %>

	<div class="form-group">
		<%= f.text_field :title, placeholder: "Title", class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.text_area :description, rows: 5, cols: 15, placeholder: "Tell us about this episode", class: "form-control" %>
	</div>

	<div class="form-group">
    <i class = "fa fa-cloud-upload fa-lq"></i><%= f.label :thumbnail %><br />
    <%= f.file_field :thumbnail %>
	</div>

	<div class="form-group">
    <i class = "fa fa-cloud-upload fa-lq"></i><%= f.label :mp3 %><br />
    <%= f.file_field :mp3 %>
	</div>

	<div class="actions">
    <%= f.submit "Save Episode", class: "btn btn-primary" %>
  </div>

<% end %>

app/views/episodes/edit.html.erb
<h1>Edit Episode</h1>

<%= render 'form' %>

app/views/episodes/new.html.erb
<h1>New Episode</h1>

<%= render 'form' %>

app/views/episodes/show.html.erb
<div class="row">
	<div class="epi-show">
		<div class="row">
		<div class="col-md-4">
			<%= image_tag @episode.thumbnail.url(:medium) %>
		</div>
		<div class="col-md-8">	
			<h3><%= @episode.title %></h3><br />
			<p><%= @episode.description %></p>
		
			<div id="jquery_jplayer_1" class="jp-jplayer"></div>
				<div id="jp_container_1" class="jp-audio">
					<div class="jp-type-single">
						<div class="jp-gui jp-interface">
							<ul class="jp-controls">
								<li><a href="javascript:;" class="jp-play" tabindex="1">&#61515;</a></li>
								<li><a href="javascript:;" class="jp-pause" tabindex="1">&#61515;</a></li>
								<li><a href="javascript:;" class="jp-mute" tabindex="1" title="mute">&#61480;</a></li>
								<li><a href="javascript:;" class="jp-unmute" tabindex="1" title="unmute">&#61478;</a></li>
							</ul>

							<div class="jp-progress">
								<div class="jp-seek-bar">
									<div class="jp-play-bar"></div>
								</div>
							</div>

							<div class="jp-time-holder">
								<div class="jp-current-time"></div>
							</div>

							<div class="jp-volume-bar">
								<div class="jp-volume-bar-value"></div>
							</div>
						
							<div class="jp-no-solution">
								<span>Update Required</span>
								To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="col-md-12 midbar">
		<ul>
			<li><%= link_to "All Podcasts", podcasts_path %></li> /
			<li><%= link_to @podcast.title, podcast_path(@podcast) %></li> /
			<li><%= @episode.title %></li>
		</ul>
	</div>
	
	<div class="container">
		<div class="row">
			<% @episodes.each do |episode| %>
				<div class="col-md-4">
					<div class="panel panel-default">
						<div class="panel-heading preview">
							<%= image_tag episode.thumbnail.url(:medium) %>
						</div>
						<div class="panel-body">
							<%= link_to episode.title, podcast_episode_path(@podcast, episode), class: "link-to-text" %>
						</div>
					</div>
				</div>
			<% end %>
		</div>
	</div>

</div>

<script>
	$(document).ready(function(){
		$("#jquery_jplayer_1").jPlayer({
			ready: function () {
				$(this).jPlayer("setMedia", {
					mp3: "<%= @episode.mp3.url %>",
				});
			},
			swfPath: "/js",
			supplied: "mp3"
		});
	});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Podcast.femXX</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'welcome' if controller_name == "welcome" && action_name == "index" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'shared/navbar' %>
<%= render "shared/message" %>

<div class="container-fluid">
	<%= yield %>
</div>

</body>
</html>

app/views/podcasts/dashboard.html.erb
<div class="jumbotron text-center">
	<h1><%= @podcast.title %> Dashboard</h1>
</div>

<div class="row">
	<div class="col-md-12 midbar">
		<ul>
			<li><%= link_to "Episodes", root_path %></li>
			<li><%= link_to "New Episode", new_podcast_episode_path(@podcast) %></li>
			<li><%= link_to "View Podcast", podcast_path(current_podcast) %></li>
		</ul>
	</div>

	<div class="wrapper-wide">
		<% @episodes.each do |episode| %>
			<div class="row dash-content">
				<div class="col-md-2">
					<%= image_tag episode.thumbnail.url, class: " thumbnail-small-sm dash-img" %>
				</div>
				<div class="col-md-8">
					<div class="dash-text-content">
						<h2><%= link_to episode.title, podcast_episode_path(@podcast, episode), class: "link-text-content" %></h2>
						<p>posted <%= episode.created_at.strftime("%B %d, %Y") %></p>
						<p><%= episode.description[0..250] %>...</p>
					</div>
				</div>
				<div class="col-md-2">
					<ul>
						<li><%= link_to "Edit", edit_podcast_episode_path(@podcast, episode), class: "btn btn-success" %></li>
						<li><%= link_to "Delete", podcast_episode_path(@podcast, episode), class: "btn btn-warning", method: :delete, data: {confirm: "Are you sure?"} %></li>
					</ul>
				</div>
			</div>
		<% end %>
	</div>
	
</div>

app/views/podcasts/index.html.erb
<div class="jumbotron">
	<h1>Discover your new favorite podcast...</h1>
</div>

<div class="container">

	<div class="row row-space-2">
		<% @podcasts.each do |podcast| %>

			<div class="col-md-4">
				<div class="panel panel-default">
					<div class="panel-heading preview">
						<%= image_tag podcast.thumbnail.url(:medium) %>
					</div>
					<div class="panel-body">
						<%= link_to podcast.title, podcast, class: "link-to-text" %><br />
						<span class="count-text"><%= podcast.episodes.count %> Episodes</span>
					</div>
				</div>
			</div>

		<% end %>

	</div>

</div>

app/views/podcasts/show.html.erb
<div class="jumbotron text-center">
	<p><%= image_tag @podcast.thumbnail.url, class: "img-circle thumbnail-xsmall" %><p>
	<h3><%= @podcast.title %> Podcast</h3>
	<p><%= @podcast.description[0..700] %></p>
	<ul>
		<% unless @podcast.itunes.blank? %>
			<li><%= link_to "iTunes", @podcast.itunes, class: "btn btn-primary" %></li>
		<% end %>
		<% unless @podcast.stitcher.blank? %>
			<li><%= link_to "Stitcher", @podcast.stitcher, class: "btn btn-primary" %></li>
		<% end %>
		<% unless @podcast.podbay.blank? %>
			<li><%= link_to "Podbay", @podcast.podbay, class: "btn btn-primary" %></li>
		<% end %>
	</ul>
</div>

<div class="midbar">
	<%= link_to "All Podcasts", podcasts_path %> /
	<%= @podcast.title %>
</div>


	<div class="wrapper-skinny">
		<% @episodes.each do |episode| %>
			<div class="row show-content">
				<div class="col-md-4">
					<%= image_tag episode.thumbnail.url, class: "thumbnail-medium show-img" %>
				</div>
				<div class="col-md-8">
					<div class="text-content">
						<h2><%= link_to episode.title, podcast_episode_path(@podcast, episode), class: "link-text-content" %></h2>
						<p>posted on <%= episode.created_at.strftime("%B %d, %Y") %></p>
						<p><%= episode.description[0..150] %>...</p>
					</div>
				</div>
			</div>
		<% end %>
	</div>

app/views/shared/_devisemsg.html.erb
<% unless resource.errors.empty? %>
	<script type="text/javascript">
		<% resource.errors.full_messages.each do |msg| %>
			toastr.error('<%= msg %>')
		<% end %>
	</script>
<% end %>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
	<script type="text/javascript">
		<% flash.each do |f| %>
			<% type = f[0].to_s.gsub('alert','error').gsub('notice','info') %>
			toastr['<%= type %>']('<%= f[1] %>')
		<% end %>
	</script>
<% end %>

app/views/shared/_navbar.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header navbar-text">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <a class="navbar-brand" href="#">Podcast.fm</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">

      <ul class="nav navbar-nav navbar-right navbar-text">
        
        <% if(!podcast_signed_in?) %>
          <li><%= link_to "Explore", podcasts_path %></li>
          <li><%= link_to "Sign In", new_podcast_session_path %></li>
          <li><%= link_to "Create a Podcast", new_podcast_registration_path %></li>

        <% else %>
          <li><%= link_to "Dashboard",root_path %></li>
          <li><%= link_to "Explore", podcasts_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <%= current_podcast.email %> <span class="caret"></span>
            </a>

            <ul class="dropdown-menu">
              <li><%= link_to "Account Settings", edit_podcast_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Sign Out", destroy_podcast_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
        
      </ul>
      
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/welcome/index.html.erb
<div class="row">
	<div class="col-md-10 col-md-offset-1 text-center">
		
		<h1>Discover your new favorite podcast, or create your own.</h1>
		<div>
			<%= link_to "Create a Podcast", new_podcast_registration_path, class: "btn btn-primary button" %>
			<%= link_to "Explore", podcasts_path, class: "btn btn-default button" %>
		</div>
		
	</div>
</div>

<script>
	$('body').addClass('home-page');
</script>

	